import { UnityArguments } from "./unity-arguments";

type UnityConfig = Pick<
  UnityArguments,
  | "dataUrl"
  | "frameworkUrl"
  | "codeUrl"
  | "companyName"
  | "productName"
  | "productVersion"
> & {
  /**
   * The url to the build json file generated by Unity. When using a relative url,
   * keep in mind this is relative from the path where your html file is served.
   * It is also possible to use an absolute url, for example when using a CDN.
   */
  readonly loaderUrl: string;
};

export type { UnityConfig };
