"use strict";
exports.__esModule = true;
var UnityContent = /** @class */ (function () {
    /**
     * Creates a new Unity content object. This object can be used
     * @param {string} buildJsonPath the relative path to the build json file generated by Unity.
     * @param {string} unityLoaderJsPath the relative path to the unity loader javascript file.
     */
    function UnityContent(buildJsonPath, unityLoaderJsPath) {
        this.buildJsonPath = buildJsonPath;
        this.unityLoaderJsPath = unityLoaderJsPath;
    }
    return UnityContent;
}());
exports["default"] = UnityContent;
