export default class UnityContent {
    /**
     * the relative path to the build json file generated by Unity.
     * @type {string}
     * @private
     */
    private buildJsonPath;
    /**
     * the relative path to the unity loader javascript file.
     * @type {string}
     * @private
     */
    private unityLoaderJsPath;
    /**
     * Creates a new Unity content object. This object can be used
     * @param {string} buildJsonPath the relative path to the build json file generated by Unity.
     * @param {string} unityLoaderJsPath the relative path to the unity loader javascript file.
     */
    constructor(buildJsonPath: string, unityLoaderJsPath: string);
}
