import IUnityConfig from "./interfaces/IUnityConfig";
import UnityComponent from "./components/Unity";
export default class UnityContent {
    /**
     * the relative path to the build json file generated by Unity.
     * @type {string}
     * @private
     */
    private buildJsonPath;
    /**
     * the relative path to the unity loader javascript file.
     * @type {string}
     * @private
     */
    private unityLoaderJsPath;
    /**
     * The Unity component binded to this content.
     */
    private unityComponentInstance?;
    /**
     * The Unity component binded to this content.
     */
    private unityPlayerInstance?;
    /**
     * the Unity configuration that will be used to start the player.
     * @type {IUnityConfig}
     * @public
     */
    unityConfig: IUnityConfig;
    /**
     * Creates a new Unity content object. This object can be used
     * @param {string} buildJsonPath the relative path to the build json file generated by Unity.
     * @param {string} unityLoaderJsPath the relative path to the unity loader javascript file.
     * @param {IUnityConfig} unityConfig the Unity configuration that will be used to start the player.
     */
    constructor(buildJsonPath: string, unityLoaderJsPath: string, unityConfig?: IUnityConfig);
    /**
     * Binds a unity component to this content.
     * @param unityComponentInstance the unity component that will be binded to this content.
     */
    setComponentInstance(unityComponentInstance: UnityComponent): void;
    /**
     * Binds a unity player to this content.
     * @param unityPlayerInstance the unity component that will be binded to this content.
     */
    setUnityPlayerInstance(unityPlayerInstance: any): void;
    /**
     * Sends an event to the Unity player that will trigger a function.
     * @param {string} gameObjectName the name of the game object in your Unity scene.
     * @param {string} methodName the name of the public method on the game object.
     * @param {any} parameter an optional parameter to pass along to the method.
     */
    send(gameObjectName: string, methodName: string, parameter?: any): void;
}
//# sourceMappingURL=UnityContent.d.ts.map