"use strict";
exports.__esModule = true;
var UnityVerions_1 = require("./enums/UnityVerions");
var UnityContent = /** @class */ (function () {
    /**
     * Creates a new Unity content object. This object can be used
     * @param {string} buildJsonPath the relative path to the build json file generated by Unity.
     * @param {string} unityLoaderJsPath the relative path to the unity loader javascript file.
     * @param {IUnityConfig} unityConfig the Unity configuration that will be used to start the player.
     */
    function UnityContent(buildJsonPath, unityLoaderJsPath, unityConfig) {
        this.buildJsonPath = buildJsonPath;
        this.unityLoaderJsPath = unityLoaderJsPath;
        var _unityConfig = typeof unityConfig === "undefined" ? {} : unityConfig;
        this.unityConfig = {
            isFullscreen: _unityConfig.isFullscreen || false,
            modules: _unityConfig.modules || {},
            unityVersion: UnityVerions_1.UnityVersion.UNITY_2018
        };
    }
    return UnityContent;
}());
exports["default"] = UnityContent;
//# sourceMappingURL=UnityContent.js.map