name: Validate Module

on:
  push:
    paths-ignore:
      - documentation/**
  pull_request:
    paths-ignore:
      - documentation/**

jobs:
  main:
    name: Main

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v3.0.0
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org

      - name: Cache Node Module Dependencies
        uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: nodemodules-${{ runner.os }}-${{ hashFiles('./package-lock.json') }}

      - name: Install Dependencies
        run: npm install

      - name: Compile Source
        run: npm run compile
