import IUnityInstanceParameters from "./unity-instance-parameters";

export default interface IUnityConfig extends IUnityInstanceParameters {
  /**
   * The url to the build json file generated by Unity. When using a relative url,
   * keep in mind this is relative from the path where your html file is served.
   * @type {string}
   */
  loaderUrl: string;
}
